export const ASSET_TYPES = ['METER', 'PUMP', 'TANK', 'PIPE', 'VALVE', 'SENSOR'];
export const UNIT_TYPES = ['CUBIC_METERS', 'LITERS', 'GALLONS'];
export const INCIDENT_SEVERITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
export const WORK_ORDER_PRIORITIES = ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'];
export const REFERENCE_TYPES = ['ASSET', 'INCIDENT', 'WORK_ORDER'];
export const REGISTER_ROLES = ['ADMIN', 'COORDINATOR', 'TECHNICIAN', 'AUDITOR'];
